services:
  - type: web
    name: projectguard-deploy
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: ./start_backend.sh
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        value: 8256079955:AAGrghwannJh_tub3Av460PRKLV0nGR_cc8
      - key: SECRET_KEY
        value: Messiah_Secret_2025
      - key: FRONTEND_URL
        value: https://projectguard-mini.onrender.com
