services:
  - type: web
    name: projectguard-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: FRONTEND_URL
        value: https://projectguard-mini.onrender.com
